### PR TITLE
Feature: hover for variables

### LINKED ISSUE #289: Add variable comments for IntelliSense (in addition to existing function comments)
**Is your feature request related to a problem? Please describe.**
Currently, you can add a comment to the function using a semicolon on the line above the function declaration, and it appears as a tooltip when you hover over the function name in the editor.

**Describe the solution you'd like**
Extend this functionality to variables, so that an in-line comment after the variable definition, or on the line above it, also appears in the tooltip.

### PR DESCRIPTION
**Pull request by kyklish**
Closes #289.

Now, working only for global variables (vars inside functions are without hover).

Notifying @mark-wiemer

### CODE REVIEW

**Comment by mark-wiemer** [comment]
Hey @kyklish , is there a reason this is still a draft?

**Comment by kyklish** [comment]
> Hey @kyklish , is there a reason this is still a draft?

It's quick `Copy& Paste` code. I did not quite understand yet, why hover not shown for local variables and do we need it at all for local variables.

I did not test, like I should.

**Review by mark-wiemer — APPROVED** [review]

**Review by mark-wiemer — CHANGES_REQUESTED** [review]
Let's also try to add the internal/external logic we have in formatter. Let's get the list of variables from the document cache and then send it to a helper function that takes a list of variables and a variable name and returns the first variable that matches the provided name. We'll call the helper with one file at a time to avoid performance issues with larger projects.

Similarly for `ahkHoverProvider.ts`, let's try to add unit tests to the return value of the modified function.

**Comment by rlitwiller89** [comment]
Would it be possible to do this for labels too?

**Pull request closed without merging**
